[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
